version: "3.8"
services:
  nextjs-app:
    build: .
    container_name: portfolio-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=https://sunilshrees.com.np
      - PORT=3000
      # Add your env vars here:
      # - DATABASE_URL=...
      # - NEXT_PUBLIC_API_URL=...
